# Generated by Django 2.2 on 2019-04-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=1000)),
                ('time', models.FloatField()),
            ],
        ),
    ]
