# Generated by Django 2.2 on 2019-04-16 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sportactivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportactivity',
            name='time',
            field=models.DurationField(),
        ),
    ]
