# Generated by Django 2.2 on 2019-04-16 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_tip'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Dish',
        ),
    ]
