# Generated by Django 2.1.7 on 2019-04-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_product_description'),
        ('accounts', '0004_auto_20190416_2212'),
    ]

    operations = [
    ]
