# Generated by Django 2.1.7 on 2019-04-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190416_1813'),
        ('accounts', '0005_merge_20190417_1321'),
    ]

    operations = [
    ]
