# Generated by Django 2.1.7 on 2019-05-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_tipstudy'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification',
            field=models.BooleanField(default=False),
        ),
    ]
