# Generated by Django 2.1.7 on 2019-05-17 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190517_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='user',
        ),
    ]
