# Generated by Django 2.1.7 on 2019-05-17 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_tip_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportActivityNotif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(default='', max_length=50)),
                ('link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='sportactivity',
            name='link',
        ),
    ]
