# Generated by Django 2.1.7 on 2019-05-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190517_1820'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SportActivityNotif',
            new_name='SportActivityNotification',
        ),
    ]
