# Generated by Django 2.1.7 on 2019-05-17 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20190517_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportactivitynotification',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sportactivitynotification', to='accounts.UserProfile'),
        ),
    ]
