# Generated by Django 2.1.7 on 2019-06-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_dish_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ingredients',
            field=models.ManyToManyField(to='accounts.Aliment'),
        ),
    ]
