# Generated by Django 2.1.7 on 2019-06-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20190602_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='accounts.Aliment'),
        ),
    ]
