# Generated by Django 2.1.7 on 2019-06-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20190602_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Aliment'),
        ),
    ]
